apiVersion: v1
kind: Service
metadata:
  name: custos-core
  labels:
    app: custos-core
spec:
  selector:
    app: custos-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
